name = "watch-repair-specialist-astro"
compatibility_date = "2024-06-18"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[[build.upload]]
format = "modules"
main = "./dist/_worker.js"
